- name: Install Python Packages
  ansible.builtin.apt:
    name:
      - python3-packaging
      - python3-pip
      - python3-virtualenv

- name: Upload poll archive
  ansible.builtin.unarchive:
    src: ../../../poll.tar
    dest: /opt
    remote_src: false

- name: Install Poll Python Requirements
  ansible.builtin.pip:
    requirements: /opt/poll/requirements.txt
    virtualenv: /opt/poll/venv

- name: Copy Poll Service file
  ansible.builtin.copy:
    src: poll.service
    dest: /etc/systemd/system/poll.service
  notify: Enable and Reload daemon

- name: Create poll environment file
  ansible.builtin.copy:
    content: |
      REDIS_HOST={{ redis_host }}
    dest: /opt/poll/poll.env

- name: Start Poll Service
  ansible.builtin.systemd_service:
    name: poll
    state: started
