- name: Apt Update && Upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"

- name: Install btop
  ansible.builtin.apt:
    name: btop

- name: Install acl
  ansible.builtin.apt:
    name: acl
    state: present

- name: Install Python Packages
  ansible.builtin.apt:
    name:
      - python3-packaging
      - python3-pip
      - python3-virtualenv
    state: present
